//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(
    feature = "ssr",
    derive(sea_orm::DeriveEntityModel),
    sea_orm(table_name = "todo")
)]
pub struct Model {
    #[cfg_attr(feature = "ssr", sea_orm(primary_key))]
    pub id: i32,
    pub title: String,
    pub completed: bool,
}

use cfg_if::cfg_if;

cfg_if! {
    if #[cfg(feature = "ssr")] {
        use sea_orm::entity::prelude::*;

        #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
        pub enum Relation {}

        impl ActiveModelBehavior for ActiveModel {}
    }
}
